[tool.poetry]
name = "inbrief-scraper"
version = "0.1.0"
description = ""
authors = ["Nikita Rydanov <wrongwayboyy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.0.2"
telethon = "^1.28.5"
python-dotenv = "^1.0.0"
tqdm = "^4.65.0"
ipykernel = "^6.23.3"
openai-api = {git = "git@github.com:kiltia/openai-api.git"}
transformers = "^4.30.2"
rb-tocase = "^1.3.2"
fasttext-wheel = "^0.9.2"
pydantic = "^2.0.3"
pydantic-settings = "^2.0.2"
torch = "^2.0.1"
fastapi = "^0.100.0"
uvicorn = "^0.23.1"


[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
