mock-request:
    echo "{}" | kcat -J -P -b "10.96.11.51:9094" -t "inbrief.embedder.in" -H correlation_id=a234b567-8901-4982-a98f-c181f8b4b3c4

read-response:
    kcat -C -t inbrief.embedder.out.json -b 10.96.11.51:9094
