mock-request:
    echo '{ \
      "chat_folder_link": "https://t.me/addlist/grg7NStE6881MDE6", \
      "left_bound": "2025-01-25T20:00:00+04:00", \
      "social": false, \
      "exporters": ["redis"] \
    }' | kcat -J -P -b "10.96.11.51:9094" -t "inbrief.scraper.in.json" -H correlation_id=a234b567-8901-4982-a98f-c181f8b4b3d9

mock-it-request:
    echo '{ \
      "chat_folder_link": "https://t.me/addlist/yFwLGgZTDZU3ZGNi", \
      "left_bound": "2024-12-01T20:00:00+04:00", \
      "social": false, \
      "exporters": ["redis"] \
    }' | kcat -J -P -b "10.96.11.51:9094" -t "inbrief.scraper.in.json" -H correlation_id=a234b567-8901-4982-a98f-c181f8b4b3d2

read-response:
    kcat -C -t inbrief.scraper.out.json -b 10.96.11.51:9094

generate-session:
    uv run python3 src/generate_session.py
